-- Create tables for portfolio website

-- Projects table
CREATE TABLE IF NOT EXISTS project (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  project_url VARCHAR(500) NOT NULL,
  image_url VARCHAR(500),
  author VARCHAR(255) NOT NULL,
  is_collaborative BOOLEAN DEFAULT FALSE,
  collaborators TEXT[] DEFAULT '{}',
  started_at TIMESTAMP WITH TIME ZONE,
  finished_at TIMESTAMP WITH TIME ZONE,
  tools_used TEXT[] DEFAULT '{}'
);

-- Avatar table
CREATE TABLE IF NOT EXISTS avatar (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url VARCHAR(500) NOT NULL
);

-- Blog table
CREATE TABLE IF NOT EXISTS blog (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  content TEXT
);

-- Enable Row Level Security (optional - disable if not needed)
-- ALTER TABLE project ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE avatar ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE blog ENABLE ROW LEVEL SECURITY;

-- Insert sample avatar (replace with your actual image URL)
INSERT INTO avatar (image_url)
VALUES ('https://example.com/avatar.jpg')
ON CONFLICT DO NOTHING;